version: "3.6"
services:
  bastion:
    image: ssh
    container_name: bastion
    expose:
      - 22/tcp
    ports:
      - 22222:22/tcp
    volumes:
      - $PWD/authorized_keys:/var/lib/bastion/authorized_keys:ro
      - bastion:/usr/etc/ssh:rw
    extra_hosts:
      - docker-host:172.28.0.1
    networks:
      bastion:
        ipv4_address: 172.28.0.2
    dns: 172.28.0.5

  docker-ssh:
    image: ssh
    container_name: docker-ssh
    expose:
      - 22/tcp
    volumes:
      - $PWD/authorized_keys:/var/lib/bastion/authorized_keys:ro
      - docker-ssh:/usr/etc/ssh:rw
    networks:
      bastion:
        ipv4_address: 172.28.0.3
    dns: 172.28.0.5

  web-server:
    image: nginx:latest
    container_name: web-server
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      bastion:
        ipv4_address: 172.28.0.4
    dns: 172.28.0.5

  dns-server:
    image: dns-server
    container_name: dns-server
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - $PWD/dns/named.conf:/etc/named.conf
      - $PWD/dns/named.rfc1912.zones:/etc/named.rfc1912.zones
      - $PWD/dns/db.example.com:/var/named/db.example.com
      - $PWD/dns/named.localhost:/var/named/named.localhost
      - $PWD/dns/named.loopback:/var/named/named.loopback
    networks:
      bastion:
        ipv4_address: 172.28.0.5
    dns: 172.28.0.5

networks:
  bastion:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
    
volumes:
  bastion:
  docker-ssh:
