version: "3.6"
services:
  bastion:
    image: ssh
    container_name: bastion
    hostname: bastion
    restart: unless-stopped
    expose:
      - 22/tcp
    ports:
      - 22222:22/tcp
    volumes:
      - $PWD/authorized_keys:/var/lib/bastion/authorized_keys:ro
      - bastion:/usr/etc/ssh:rw
    extra_hosts:
      - docker-host:172.28.0.1
    networks:
      bastion:
        ipv4_address: 172.28.0.2

  docker-ssh:
    image: ssh
    container_name: docker-ssh
    hostname: docker-ssh
    restart: unless-stopped
    expose:
      - 22/tcp
    volumes:
      - $PWD/authorized_keys:/var/lib/bastion/authorized_keys:ro
      - docker-ssh:/usr/etc/ssh:rw
    networks:
      bastion:
        ipv4_address: 172.28.0.3

networks:
  bastion:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
    
volumes:
  bastion:
  docker-ssh:
